# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - iscsacra

on:
  push:
    branches:
      - sacra
      - Production
  pull_request:
    branches:
      - sacra
      - Production
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
    
      - name: copy .env.example to .env
        run: cp .env.example .env

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Generate application key
        run: php artisan key:generate

      - name: directory permissions
        run: sudo chmod -R 777 storage bootstrap/cache
      - name: create database
        run: mkdir -p /tmp/database && touch /tmp/database/database.sqlite

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_252255B4490E4B7AAF031700829FA2C6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A82BD2EAB37746DA99DD1F232AADD469 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FCF0C81BAB994BDCB4DF248D02DF720A }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'iscsacra'
          slot-name: 'Production'
          package: .
          